name: first secret yml
on:
  workflow_dispatch:
jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: check if secret is set
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then 
          echo "Secret is not set"
          else
          echo "Secret is set"
          fi
      - name: print secret
        run: echo "The secret message is :" ${{ secrets.MY_SECRET_MESSAGE }}