jobs:
  matrix:
  runs-on: ${{ matrix.os }}
  strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Always wrap version numbers in quotes to prevent YAML truncation
        python-version: ['3.10', '3.11', '3.12'] 

    steps:
      - name: Set up job
        uses: actions/checkout@v4

      - name: installing python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
