name: reusable workflow

on:
  workflow_call:

    inputs:

      app_name:
        description: 'name of your app'
        type: string
        required: true

      environment:
        description: 'Environment to deploy to'
        type: string
        default: 'staging'
        required: true

    secrets:

      docker_token:
        required: true

    outputs:

      build_version:
        description: build version information
        value: ${{ jobs.reusable.outputs.version }}

jobs:
  
  reusable:
    runs-on: ubuntu-latest
    outputs:
      version: 'v1.0-${{ steps.set.outputs.SHORT_SHA }}'

    steps:
      
      - name: code checkout
        uses: actions/checkout@v4

      - name: app name & environment
        run: echo  "Building ${{ inputs.app_name }} for  ${{ inputs.environment }}"

      - name: Check docker token 
        run: |
          if [ -z ${{ secrets.docker_token }} ]; then
            echo "Docker token is set: false"
          else
            echo "Docker token is set: true"
          fi

      - name: Set build version value
        id: set
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "$SHORT_SHA"
        
    