name: publish docker of simple-java-docker

on:
  workflow_dispatch:
  #push:
  #pull_request:
    #types: [opened, synchronize] 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: code checkout
        uses: actions/checkout@v4
        with:
          filter: blob:none
          sparse-checkout: |
            simple-java-docker
          sparse-checkout-cone-mode: false

      #- name: Build docker image
       # working-directory: ./simple-java-docker
        #run: docker build -t simple-java-docker .
      #- name: Tag docker images
       # run: docker tag simple-java-docker ${{ vars.DOCKER_USERNAME }}/simple-java-docker:latest
      
      - name: LogIn to Docke Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Shorten github sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push image to Docker Hub if pushed from main
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: ./simple-java-docker
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/simple-java-docker:latest
            ${{ vars.DOCKER_USERNAME }}/simple-java-docker:${{ env.SHORT_SHA }}

      - name: Build image  if pushed from other branches or on pull request
        if: github.ref_name != 'main'
        uses: docker/build-push-action@v6
        with:
          context: ./simple-java-docker
          push: false
          tags: |
            ${{ vars.DOCKER_USERNAME }}/simple-java-docker:latest
            ${{ vars.DOCKER_USERNAME }}/simple-java-docker:${{ env.SHORT_SHA }}