name: Run Tests

on:
  push:

jobs:
 
  test:
    runs-on: ubuntu-latest

    steps:
      
      - name: print test
        run: |
          echo "Runnign from test workflow"
          echo "All tests done for :$(date)"
          echo '"All tests done on :${{ runner.os }}"'

      - name: FAIL
        run: exit 1